<?php

return [
    [
        'name' => 'swiperInfo',
        'title' => '焦点图',
        'type' => 'gallery',
        'content' => [],
        'value' => '[{"image":"/assets/addons/miniform/img/swiper1.jpg","title":"旅游度假好去处123","path":"/pages/index/index"},{"image":"/assets/addons/miniform/img/swiper2.jpg","title":"欢迎您的光临！","path":"/pages/detail/detail?id=1"}]',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wxapp',
        'title' => '小程序二维码',
        'type' => 'image',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'index_list',
        'title' => '首页默认排版',
        'type' => 'radio',
        'content' => [
            1 => '列表',
            0 => '简图',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '首页默认排版',
        'extend' => '',
    ],
    [
        'name' => 'isShowNavInMp',
        'title' => '在公众号是否显示顶部导航',
        'type' => 'radio',
        'content' => [
            1 => '显示',
            0 => '隐藏',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'order_timeout',
        'title' => '订单超时时长',
        'type' => 'number',
        'content' => [],
        'value' => '1800',
        'rule' => 'required',
        'msg' => '',
        'tip' => '超时订单将自动关闭，单位秒',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'critical_timeout',
        'title' => '消息临界时间',
        'type' => 'number',
        'content' => [],
        'value' => '86400',
        'rule' => 'required',
        'msg' => '',
        'tip' => '签到时间或项目结束时间还剩多少时间推送消息，单位秒',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'order_refund_sync',
        'title' => '订单同步退款',
        'type' => 'radio',
        'content' => [
            1 => '是',
            0 => '否',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '如需启用，请先配置微信支付宝整合插件',
        'extend' => '',
    ],
    [
        'name' => 'signin_distance',
        'title' => '签到最小范围',
        'type' => 'number',
        'content' => [],
        'value' => '500',
        'rule' => 'required',
        'msg' => '',
        'tip' => '签到的最小范围，单位米(m)',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'camera_qrcode',
        'title' => '摄像头扫码核销(部分浏览器不支持)',
        'type' => 'radio',
        'content' => [
            1 => '是',
            0 => '否',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '使用手机或PC自带的摄像头进行扫码核销，部分浏览器不支持',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'verification_voice',
        'title' => '核销成功声音提示',
        'type' => 'radio',
        'content' => [
            1 => '是',
            0 => '否',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '开启后核销成功将会有语音提示',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wx_appid',
        'title' => '小程序AppID',
        'type' => 'string',
        'content' => [],
        'value' => 'wx4709f21d428b30e6',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wx_app_secret',
        'title' => '小程序AppSecret',
        'type' => 'string',
        'content' => [],
        'value' => 'a940251c12d875602a323e732cda77f4',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'mobile',
        'title' => '联系电话',
        'type' => 'string',
        'content' => [],
        'value' => '18888888888',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'app_id',
        'title' => 'APP的AppID',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '微信开放平台中应用的Appid，仅Uniapp版本使用',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'app_secret',
        'title' => 'APP的AppSecret',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '微信开放平台中应用的AppSecret，仅Uniapp版本使用',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'alipay_app_id',
        'title' => '支付宝小程序的AppID',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '支付宝开发平台的AppID，仅Uniapp版本使用',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'verification_key',
        'title' => '核销码加密的key',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '默认使用框架中的token.key值，建议随机生成',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sendnoticemode',
        'title' => '通知推送模式',
        'type' => 'radio',
        'content' => [
            'disabled' => '关闭推送',
            'async' => '异步并发推送',
            'queue' => '使用队列推送(需安装队列插件+Redis)',
        ],
        'value' => 'disabled',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'agreement',
        'title' => '注册协议',
        'type' => 'editor',
        'content' => [],
        'value' => '注册协议',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
